Logging:
  LogLevel:
    Default: Warning

MaterialPurchaseDb:
  ConnectionString: Data source=purplesql;Initial catalog=MaterialPurchase;User Id=usr_material-purchase-api;Connection Timeout=30;TrustServerCertificate=True;Application Name=material-purchase-api

AzureAdSettings:
    ClientId: 4ca0a025-7563-4aa4-a6ba-a9484a1bbc9e
    Audience: https://material-purchase-api.notino.app

SwaggerAuthOptions:
    ClientId: 5a61ccea-05d5-4dad-b728-75e7939130aa
    Scope: https://material-purchase-api.notino.app/api.read.write