apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: material-supplying

commonAnnotations:
  app.notino.com/technology: dotnet
  app.notino.com/responsible-team: group:default/purchase
  backstage.io/kubernetes-id: material-purchase-api

commonLabels:
  name: material-purchase-api
  app: material-purchase-api
  app.kubernetes.io/name: material-purchase-api
  app.kubernetes.io/instance: material-purchase-api
  app.kubernetes.io/managed-by: notino-auto-devops
  app.kubernetes.io/part-of: material-supplying
  app.kubernetes.io/component: api

resources:
  - ./api/deployment.yaml
  - ./api/ingress.yaml
  - ./api/service.yaml

transformers:
  - versionTransformer.yaml