apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: material-supplying

configMapGenerator:
  - files:
      - ./configs/k8sappsettings.yaml
    name: material-purchase-api-config

generatorOptions:
  disableNameSuffixHash: true

bases:
  - ../../bases

patchesStrategicMerge:
  - ./api/deployment.yaml
  - ./api/ingress.yaml

resources:
  - ./api/pdb.yaml
  - serviceAccount.yaml